version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: identitylink-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nuthan.iiit
      POSTGRES_DB: identitylink

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: identitylink-backend

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: postgresql://postgres:nuthan.iiit@postgres:5432/identitylink

volumes:
  postgres_data: